# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1818db5434c0aff3ae709ff14a0e28d34b9fa9c55dd4273cd81de94995a90058b7b94ab069451932fd139ef72c3c80301d3436cd852cc653c87baec1925a09d3

test:
  secret_key_base: 315e3ee0c98a47665a45ea7e8460df684df6b27e5c33600f4e5715a5cefe736e5555d6c63ff7d25c0f8123d6a58723939c1f95b8b6280eed94911489a2a31d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
